spring:
  profiles:
    active:
      - dev
---

spring:
  profiles: dev #正式环境
  application:
    name: config-server-dev

---


spring:
  profiles: test #测试环境
  application:
    name: config-server-test
