
server.port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://eureka-01.com:8081/eureka/
  instance:
    instance-id: server-id-dev
spring:
  profiles: dev #正式环境
  application:
    name: config-server-dev
  

---

server.port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://eureka-02.com:8082/eureka/
  instance:
    instance-id: server-id-test
spring:
  profiles: test #测试环境
  application:
    name: config-server-test